# Generated by Django 3.2 on 2022-06-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorandstandardasset',
            options={'ordering': ['-asa_id'], 'verbose_name': 'Algorand Standard Asset', 'verbose_name_plural': 'Algorand Standard Assets'},
        ),
        migrations.AlterField(
            model_name='retweetuser',
            name='lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
